#!/usr/bin/env sh

echo "RUNNING POST MERGE"

REPO_ROOT="$(git rev-parse --show-toplevel)"

echo "updating dependencies..."
npm --prefix "$REPO_ROOT" ci --ignore-scripts
npm --prefix "$REPO_ROOT/frontend" ci --ignore-scripts

echo "POST-MERGE COMPLETE"